### ISSUE TITLE
Support visual mode smartgf

### ISSUE THREAD

**Issue by pgilad** [gorkunov/smartgf.vim#11]
Currently only normal mode is supported, and there are no exposed mappings in order to manually bind keys to other modes.

I suggest exposing `<plug>` that user can map himself keys to whichever modes he wants.

See https://github.com/tyru/open-browser.vim/blob/master/plugin/openbrowser.vim#L233-L238 as an example

**Comment by pgilad** [comment]
@gorkunov Will you accept a PR for this?

**Comment by gorkunov** [comment]
@pgilad yep!
